spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 9029
  session-timeout: 1000
  servlet:
    context-path: /demo

# 打印sql
logging:
  level:
    com.**.mapper: debug